# Generated by Django 5.1.5 on 2025-04-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_add', models.DateField(auto_now_add=True, null=True)),
                ('update', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=15)),
                ('created_add', models.DateField(auto_now_add=True, null=True)),
                ('update', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
